---

# - name: install nmap
#   apt:
#     update_cache: yes
#     name: "{{ packages }}"
#   vars:
#     packages:
#     - nmap

- name: create tmp file for nmap xml nmap_results
  file:
    path: /tmp/nmap_results
    state: touch


- name: get all the connected hosts
  shell: nmap -sn 192.168.0.1/24 -oG nmap_results
  args:
    chdir: /tmp
    warn: no

- name: retrieve the greppable nmap_results 
  slurp:
    src: /tmp/nmap_results
  register: possible_pi_zero

- name: Show an attribute value
  debug:
    var: "{{ item }}"
  loop: "{{ possible_pi_zero.stdout_lines }}"

# - name: Display all the ips
#   debug: 
#     msg: "{{ item }}"
#   loop: "{{nmap_output.stdout_lines}}"

# - name: pull out the lines with Raspberry Pi Mac Addresses
#   debug: 
#     msg: "{{ item }}"
#   loop: "{{nmap_output.stdout_lines}}"
#   when: item.find('Raspberry Pi Foundation') !=- 1
