---
- hosts: 127.0.0.1
  become: yes
  connection: local
  roles:
    - { role: sys/hat-poweron }
    # - { role: sys/pizero-discover }
    - {  role: sys/controller-update }

- hosts: pizero
  gather_facts: yes
  become: yes
  roles:
    - { role: sys/pizero-update }

# - hosts: pizero
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: docker/controller-install }

# - hosts: pizero
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: docker/zero-install }

# - hosts: pizero, controller
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: docker/common-install }

- hosts: pizero    
  gather_facts: yes
  become: yes
  roles:
    - { role: sys/pizero-shutdown }

- hosts: 127.0.0.1    
  connection: local
  become: yes
  roles:
    - { role: sys/hat-shutdown }